// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // GoogleService-Info.plist 기반 iOS 옵션
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbJrJ7e2RPkydQD5O8N2MOpG9ei0QnU_s',
    appId: '1:69323558263:ios:1c322b54a65fe6d6d9e572',
    messagingSenderId: '69323558263',
    projectId: 'chimshin-bible-note',
    storageBucket: 'chimshin-bible-note.firebasestorage.app',
    iosBundleId: 'com.logosflow.chimshinBibleNote',
    iosClientId: '69323558263-igolba302p8kc6h023t3k1v2rhhnmevh.apps.googleusercontent.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbJrJ7e2RPkydQD5O8N2MOpG9ei0QnU_s',
    appId: '1:69323558263:ios:1c322b54a65fe6d6d9e572',
    messagingSenderId: '69323558263',
    projectId: 'chimshin-bible-note',
    storageBucket: 'chimshin-bible-note.firebasestorage.app',
    iosBundleId: 'com.logosflow.chimshinBibleNote',
    iosClientId: '69323558263-igolba302p8kc6h023t3k1v2rhhnmevh.apps.googleusercontent.com',
  );
}
